### ISSUE TITLE
Scrambled, dark picture rendering

### ISSUE THREAD

**Issue by Passiday** [rien/reStream#102]
Hi, while I can successfully connect to my reMarkable, I'm getting bad picture:

![Screenshot from 2024-01-18 12-11-59](https://github.com/rien/reStream/assets/1238666/e75fd8a4-1dc1-4e89-a951-f7553eea2643)

I'm using
- reStream 1.2.0
- on Ubuntu 22.04.3 LTS
- ffmpeg version 4.4.2-0ubuntu0.22.04.1
- ffplay version 4.4.2-0ubuntu0.22.04.1

The picture is dark, there's some misalignment of lines going on. However, one can still see some remnants of the actual picture. In this screenshot, I have opened Release 3.9 info page. You can see "Lefties' relief" subtitle, in black letters, mirrored, bottom-to-top direction.

There are no error/warning messages in the terminal.

**Comment by rien** [comment]
Hi, this was indeed a problem since a recent firmware update and has been fixed in #101. Updating to version [v1.3.1](https://github.com/rien/reStream/releases/tag/v1.3.1) should fix this issue.

**Comment by Passiday** [comment]
Well I downloaded the [reStream.sh from the v1.3.1](https://github.com/rien/reStream/releases/download/v1.3.1/reStream.sh), but the problem still says. The line 4 of the file also still says `version="1.2.0"`.

**Comment by rien** [comment]
Ah, hmm, that is indeed an issue.

Can you look at line 173? It should look something like this:
https://github.com/rien/reStream/blob/006d83e9b80fb2f3dd9db2330cce5e967d3df51a/reStream.sh#L173

If that is the case, can you try changing it back to the previous settings:
https://github.com/rien/reStream/blob/333da2a5e56601ea9d17190998aa04280392c9a2/reStream.sh#L173

I unfortunately don't have a reMarkable 2 to try a fix, so you will have to experiment a bit to see what works for you.

**Comment by Passiday** [comment]
Yes, it's one in commit [006d83e](https://github.com/rien/reStream/commit/006d83e9b80fb2f3dd9db2330cce5e967d3df51a).
But I get a good picture now, so there's no need to fix anything.
As for your suggestiong, I tried also to change the line to the version from commit [333da2a](https://github.com/rien/reStream/commit/333da2a5e56601ea9d17190998aa04280392c9a2), and it sill looks fine.
